### ISSUE TITLE
Det funkar inte

### ISSUE THREAD

**Issue by Palsson123** [ceniklas/prettyflyforakiteguy#1]
Hej,

Appen fungerar inte och jag har kraschat min drake,
jag ser gärna att du betala för skadorna som har uppstått på min drake som jag har döpt efter min hund (charlie).

Jag har inte testat appen men det är mitt antagande att den inte fungerar.

Mvh,
Jakob

**Comment by Palsson123** [comment]
BUMP

**Comment by ceniklas** [comment]
Fast den fungerar jättebra ju. Din hund luktar förmodligen bara illa och behöver ett bad. Har du provat att starta om appen?

**Comment by ceniklas** [comment]
PS: Den har iallafall inga j*vla semikolon.

**Comment by Palsson123** [comment]
> Hej jag heter Niklas och är ful

Så låter du

**Comment by ceniklas** [comment]
Onödigt! <3
